### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by martinpaljak** [crocs-muni/javacard-curated-list#1]
See https://github.com/seek-for-android/allow-all-ara/blob/master/com/gieseckedevrient/javacard/allowall/AllowAll.java and https://github.com/martinpaljak/GlobalPlatformPro/pull/82

**Comment by petrs** [comment]
Thank you, added into Applet build, upload and management part of the list - although I need to investigate further what this means. Is this relevant for JavaCard applets on SIM for Android, or elsewhere as well?
