### ISSUE TITLE
Update: OpenJavaCard (ex javacard-ndef)

### ISSUE THREAD

**Issue by promovicz** [crocs-muni/javacard-curated-list#5]
In the recent months I have been reforming my various JavaCard work into an umbrella project called OpenJavaCard. The javacard-ndef project is now called openjavacard-ndef and has been moved. Proper GitHub redirects are in place, but you might still want to update the corresponding entry.

Apart from that the OpenJavaCard project contains other projects, too: @OpenJavaCard.

**Comment by petrs** [comment]
Hi Ingo, 
I overlooked this issue, please accept my apology. Your project looks really nice and https://openjavacard.org in particular aims to the same goals as we do (@enigmabridge, @croc-muni and @OpenCryptoProject). I'm wondering if you would have some time for quick chat how to unite the forces? At least to provide single clear guide about main fragments projects in open javacard space (devel tools, end-user applets, crypto  code snippets etc.) and what is necessary for further adoption  (this curated list is listing all projects without sorting out the most important ones or giving the guidance for missing ones)

Regarding this issue in particular, I updated javacard-ndef  location. What else would you like to add?

**Comment by promovicz** [comment]
Thanks for the attention. No need for an apology.

I would indeed like to chat about joining forces, and you are most welcome. I will contact you about that by E-Mail in the next few days. Setting up some sort of open project communications (mailing list, forum, web chat) is also on my To-Do-List.

With regards to listing projects I think that you should include openjavacard-tools, my alternative take on a GlobalPlatform host implementation. It is probably the most mature of the OJC projects and is approaching a beta-release state as both a command-line tool and a reusable library.

You can also list openjavacard-libraries, which is intended to become a common class library for JavaCard. This has a long way to go though. It currently contains an RSA-OAEP implementation, a TLV library and some Debug support code (exception catcher/resolver).

**Comment by petrs** [comment]
Drop me an email once ready - I'm buried right now, but at least we can discuss the future steps
